[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["corepack enable && corepack prepare pnpm@9 --activate && pnpm install --frozen-lockfile && pnpm --filter database db:generate"]

[phases.build]
cmds = ["pnpm --filter server build"]

[start]
cmd = "corepack enable && corepack prepare pnpm@9 --activate && pnpm --filter database db:deploy && pnpm --filter server start"